# Creando Matrices con NumPy

In [52]:
ls "C:/Users/Administrator/PracticaNumPy.ipynb"

 Volume in drive C is Windows
 Volume Serial Number is 3C19-4769

 Directory of C:\Users\Administrator



File Not Found


In [4]:
import numpy as np
from scipy import sparse

In [5]:
#Creando una fila
vector_row = np.array([1, 2, 3])
vector_row

array([1, 2, 3])

In [6]:
#Creando una columna
vector_column = np.array([[1],[2],[3]])
vector_column

array([[1],
       [2],
       [3]])

In [7]:
#Creando una matriz
matrix = np.array([[1,2],
                  [1,2],
                  [1,2]])

matrix

#Sino...
OtraMatrix = np.mat([[1,2],
                   [1,2],
                   [1,2]])

print(OtraMatrix + matrix)

[[2 4]
 [2 4]
 [2 4]]


In [8]:
#Creando Matriz dispersa (sparse matrix)--> cuando la mayoría de los elementos son ceros. 
#Esto se usa para que no ocupe tanto espacio a nivel computacional

matriz = np.array([[0,0],
                   [0,1],
                   [3,0]])
matriz

matriz_sparse = sparse.csr_matrix(matriz)

print(matriz_sparse)

# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])


matrix_large_CSR = sparse.csr_matrix(matrix_large)

print(matrix_large_CSR)

#Como se puede apreciar, no importa si la cantidad de ceros es mayor, sino si se acumulan o no en memoria a nivel de bytes

  (1, 1)	1
  (2, 0)	3
  (1, 1)	1
  (2, 0)	3


In [9]:
#Seleccionando elementos de los vectores
vector = np.array([1,2,3,4,5,6])

Matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

#Selecciono 3er valor
print(vector[2])
#Selecciono 2da fila, 2da columna
print(Matrix[1,1])

#Selecciono todos los elementos del vector
print(vector[:])

#Selecciono todo hasta el 3er elemento
print(vector[:3])

#Selecciono todo después del 3er elemento
print(vector[3:])

#Selecciono último elemento
print(vector[-1])

#Selecciono primeras dos filas y todas las columnas de la matriz
print(Matrix[:2,:])

#Selecciono toda las filas y la segunda columna
print(Matrix[:,1:2])

3
5
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6
[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]


In [10]:
#Describiendo Matrices
MatriX = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])

#Dimensiones matrices, en este caso 3 filas y 4 columnas
print(MatriX.shape)

#Número de elementos dentro de la matriz (filas*columnas)
print(MatriX.size)

#Número de dimensiones de la matriz
print(MatriX.ndim)

(3, 4)
12
2


In [11]:
#Operaciones con matrices
Matrics = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

#Multiplico cada elemento *100
print(Matrix*100)

#Tmb puedo crear funciones vectorizadas que se aplican a cada elemento de la lista a modo de for loop

add_1 = lambda i: i+1 #Creo función lambda para sumarle 1 a cada elemento de la matriz

vectorized_add_1 = np.vectorize(add_1)

print(add_1(Matrics))

[[100 200 300]
 [400 500 600]
 [700 800 900]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [12]:
#Min, Max, average, variance y std deviation

Metriz = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

#Min
print(np.min(Metriz))

#Max
print(np.max(Metriz))

#Mean
print(np.mean(Metriz))

#Variance
print(np.var(Metriz))

#Std Deviation
print(np.std(Metriz))

#Tmb puedo aplicarlo a nivel fila o columna

print(np.mean(Metriz,axis=0)) #a nivel columna
print(np.mean(Metriz,axis=1)) #a nivel fila

1
9
5.0
6.666666666666667
2.581988897471611
[4. 5. 6.]
[2. 5. 8.]


In [13]:
#Reconvertir la forma de las matrices
Matrixx = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [10,11,12]])

#Reconvierto Matrixx en 2x6 en vez de 4x3
print(Matrixx.reshape(2,6))

#Si queremos decirle "las columnas que sean necesarias" usamos el -1
print(Matrixx.reshape(3,-1))

#Si sólo usamos pasamos unn int como argumento, se creará un array de 1 dimensión con los elementos de la matriz

print(Matrixx.reshape(12))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [17]:
#Trasponer la matriz
print(Metriz.T)

#Hacer la matriz de un solo array/vector
print(Metriz.flatten())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6 7 8 9]


In [18]:
#Rango de una matriz
Matrixxx = np.array([[1,1,1],
                    [1,1,10],
                    [1,1,15]])

print(np.linalg.matrix_rank(Matrixxx))


2


In [21]:
#Calcular determinante de la matriz
print(np.linalg.det(Metriz))

#Calcular diagonal de la matriz
print(np.diagonal(Metriz))

#Traza de la matriz
print(Metriz.trace())

-9.51619735392994e-16
[1 5 9]
15


In [26]:
#Calcular Eigenvalues matriz cuadrada
Matrixxxx = np.array([[1,-1,3],
                    [1,1,6],
                    [3,8,9]])

eigenvalues, eigenvectors = np.linalg.eig(Matrixxxx)

print(eigenvalues)

print(eigenvectors)

[13.55075847  0.74003145 -3.29078992]
[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


In [31]:
#Operaciones

#Multiplicación de vectores
vectorr = np.array([1,2,3])

vectorrr = np.array([4,5,6])

print(np.dot(vectorr,vectorrr))

#Suma de matrices
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

print(matrix_a + matrix_b)

#Resta
print(matrix_a - matrix_b)

#Multiplicación
print(matrix_a*matrix_b)

32
[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]
[[ 1  3  1]
 [ 1  3  1]
 [ 1  3 16]]


In [37]:
#Matriz inversa
print(np.linalg.inv(Metriz))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [59]:
#Crear elementos random entre 0 y 1. El seed sirve para salvar los mismos números random. 
np.random.seed(0)

print(np.random.random(3))

#Tmb puedo generar números enteros

print(np.random.randint(0,11,3))



[0.5488135  0.71518937 0.60276338]
[3 7 9]
